/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;



/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Ventana_Inicio_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Inicio_Admin
     */
    public Ventana_Inicio_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("Unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JButton();
        BotonClientes = new javax.swing.JButton();
        BotonArticulos = new javax.swing.JButton();
        BotonProveedores = new javax.swing.JButton();
        BotonConsultas = new javax.swing.JButton();
        BotonAjustes = new javax.swing.JButton();
        BotonHome = new javax.swing.JButton();
        BotonAyuda = new javax.swing.JButton();
        VentanaInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StatusUsuario = new javax.swing.JLabel();
        RolUsuario = new javax.swing.JLabel();
        FotoUsuario = new javax.swing.JLabel();
        Animación = new javax.swing.JLabel();
        Sombra = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(null);
        setLocation(new java.awt.Point(4, -4));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(870, 450));
        setMinimumSize(new java.awt.Dimension(870, 450));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(870, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Boton - cerrado - before.png"))); // NOI18N
        BotonCerrar.setBorderPainted(false);
        BotonCerrar.setContentAreaFilled(false);
        BotonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonCerrar.setDefaultCapable(false);
        BotonCerrar.setMargin(null);
        BotonCerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Boton - cerrado.png"))); // NOI18N
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCerrar);
        BotonCerrar.setBounds(840, 0, 30, 30);

        BotonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/clientes - before - gris.png"))); // NOI18N
        BotonClientes.setBorderPainted(false);
        BotonClientes.setContentAreaFilled(false);
        BotonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonClientes.setDefaultCapable(false);
        BotonClientes.setMargin(null);
        BotonClientes.setMaximumSize(new java.awt.Dimension(174, 38));
        BotonClientes.setMinimumSize(new java.awt.Dimension(174, 38));
        BotonClientes.setPreferredSize(new java.awt.Dimension(174, 38));
        BotonClientes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/clientes - pressed - gris.png"))); // NOI18N
        BotonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClientesActionPerformed(evt);
            }
        });
        getContentPane().add(BotonClientes);
        BotonClientes.setBounds(30, 140, 180, 40);

        BotonArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Articulos - before - gris.png"))); // NOI18N
        BotonArticulos.setBorderPainted(false);
        BotonArticulos.setContentAreaFilled(false);
        BotonArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonArticulos.setDefaultCapable(false);
        BotonArticulos.setMargin(null);
        BotonArticulos.setMaximumSize(new java.awt.Dimension(174, 38));
        BotonArticulos.setMinimumSize(new java.awt.Dimension(174, 38));
        BotonArticulos.setPreferredSize(new java.awt.Dimension(174, 38));
        BotonArticulos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Articulos - pressed - gris.png"))); // NOI18N
        getContentPane().add(BotonArticulos);
        BotonArticulos.setBounds(30, 200, 180, 40);

        BotonProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Proveedores - before - gris.png"))); // NOI18N
        BotonProveedores.setBorderPainted(false);
        BotonProveedores.setContentAreaFilled(false);
        BotonProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonProveedores.setMargin(null);
        BotonProveedores.setMaximumSize(new java.awt.Dimension(174, 38));
        BotonProveedores.setMinimumSize(new java.awt.Dimension(174, 38));
        BotonProveedores.setPreferredSize(new java.awt.Dimension(174, 38));
        BotonProveedores.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Proveedores - pressed - gris.png"))); // NOI18N
        getContentPane().add(BotonProveedores);
        BotonProveedores.setBounds(30, 260, 180, 50);

        BotonConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Consultas - before - gris.png"))); // NOI18N
        BotonConsultas.setBorderPainted(false);
        BotonConsultas.setContentAreaFilled(false);
        BotonConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonConsultas.setMargin(null);
        BotonConsultas.setMaximumSize(new java.awt.Dimension(174, 38));
        BotonConsultas.setMinimumSize(new java.awt.Dimension(174, 38));
        BotonConsultas.setPreferredSize(new java.awt.Dimension(174, 38));
        BotonConsultas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Consultas - pressed - gris.png"))); // NOI18N
        getContentPane().add(BotonConsultas);
        BotonConsultas.setBounds(30, 330, 180, 40);

        BotonAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Configuración - before.png"))); // NOI18N
        BotonAjustes.setBorderPainted(false);
        BotonAjustes.setContentAreaFilled(false);
        BotonAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonAjustes.setDefaultCapable(false);
        BotonAjustes.setMargin(null);
        BotonAjustes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Configuración - pressed.png"))); // NOI18N
        getContentPane().add(BotonAjustes);
        BotonAjustes.setBounds(810, 0, 30, 30);

        BotonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Home - before.png"))); // NOI18N
        BotonHome.setBorderPainted(false);
        BotonHome.setContentAreaFilled(false);
        BotonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonHome.setDefaultCapable(false);
        BotonHome.setMargin(null);
        BotonHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Home - pressed.png"))); // NOI18N
        BotonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonHomeMousePressed(evt);
            }
        });
        getContentPane().add(BotonHome);
        BotonHome.setBounds(200, 410, 30, 30);

        BotonAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ayuda - before.png"))); // NOI18N
        BotonAyuda.setBorderPainted(false);
        BotonAyuda.setContentAreaFilled(false);
        BotonAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonAyuda.setDefaultCapable(false);
        BotonAyuda.setMargin(null);
        BotonAyuda.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ayuda - pressed.png"))); // NOI18N
        BotonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAyuda);
        BotonAyuda.setBounds(20, 410, 40, 30);

        VentanaInicio.setBackground(new java.awt.Color(0, 0, 0));
        VentanaInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 200, 0)));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 200, 0));
        jLabel1.setText("EN PROCESO...");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout VentanaInicioLayout = new javax.swing.GroupLayout(VentanaInicio);
        VentanaInicio.setLayout(VentanaInicioLayout);
        VentanaInicioLayout.setHorizontalGroup(
            VentanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaInicioLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        VentanaInicioLayout.setVerticalGroup(
            VentanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaInicioLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        getContentPane().add(VentanaInicio);
        VentanaInicio.setBounds(270, 110, 580, 320);

        StatusUsuario.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        StatusUsuario.setForeground(new java.awt.Color(0, 153, 0));
        StatusUsuario.setText("» ONLINE");
        StatusUsuario.setToolTipText("Status");
        StatusUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        StatusUsuario.setName("Status"); // NOI18N
        StatusUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StatusUsuarioMousePressed(evt);
            }
        });
        getContentPane().add(StatusUsuario);
        StatusUsuario.setBounds(360, 50, 100, 17);

        RolUsuario.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        RolUsuario.setForeground(new java.awt.Color(242, 199, 0));
        RolUsuario.setText("ADMIN");
        RolUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(RolUsuario);
        RolUsuario.setBounds(360, 20, 50, 30);

        FotoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/UsuarioFoto.png"))); // NOI18N
        FotoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(FotoUsuario);
        FotoUsuario.setBounds(270, 20, 81, 80);

        Animación.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/left-bar-Gif-.gif"))); // NOI18N
        getContentPane().add(Animación);
        Animación.setBounds(0, 0, 245, 450);

        Sombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/left - bar - imagen.png"))); // NOI18N
        getContentPane().add(Sombra);
        Sombra.setBounds(0, 0, 290, 450);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Background.png"))); // NOI18N
        Background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BackgroundMouseDragged(evt);
            }
        });
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackgroundMousePressed(evt);
            }
        });
        getContentPane().add(Background);
        Background.setBounds(0, 0, 870, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonCerrarActionPerformed
int xx, xy;
    private void BackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMousePressed
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_BackgroundMousePressed

    private void BackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_BackgroundMouseDragged

    private void BotonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonClientesActionPerformed

    private void BotonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAyudaActionPerformed
    
    boolean conect = true;
    private void StatusUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusUsuarioMousePressed
       
        if (conect == true) {
             StatusUsuario.setText("» DESCONECTADO");
             StatusUsuario.setForeground(new java.awt.Color(155, 47, 47));
             conect = false;
        }else {
            StatusUsuario.setForeground(new java.awt.Color(0, 153, 0));
            StatusUsuario.setText("» ONLINE");
            conect = true;
        }
     
    }//GEN-LAST:event_StatusUsuarioMousePressed

    private void BotonHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHomeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonHomeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Inicio_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ventana_Inicio_Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Animación;
    private javax.swing.JLabel Background;
    private javax.swing.JButton BotonAjustes;
    private javax.swing.JButton BotonArticulos;
    private javax.swing.JButton BotonAyuda;
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JButton BotonClientes;
    private javax.swing.JButton BotonConsultas;
    private javax.swing.JButton BotonHome;
    private javax.swing.JButton BotonProveedores;
    private javax.swing.JLabel FotoUsuario;
    private javax.swing.JLabel RolUsuario;
    private javax.swing.JLabel Sombra;
    private javax.swing.JLabel StatusUsuario;
    private javax.swing.JPanel VentanaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

 
}
